#!/bin/bash
#
# @file clearwater-socket-factory-wrapper
#
# Project Clearwater - IMS in the Cloud
# Copyright (C) 2016  Metaswitch Networks Ltd
#
# This program is free software: you can redistribute it and/or modify it
# under the terms of the GNU General Public License as published by the
# Free Software Foundation, either version 3 of the License, or (at your
# option) any later version, along with the "Special Exception" for use of
# the program along with SSL, set forth below. This program is distributed
# in the hope that it will be useful, but WITHOUT ANY WARRANTY;
# without even the implied warranty of MERCHANTABILITY or FITNESS FOR
# A PARTICULAR PURPOSE.  See the GNU General Public License for more
# details. You should have received a copy of the GNU General Public
# License along with this program.  If not, see
# <http://www.gnu.org/licenses/>.
#
# The author can be reached by email at clearwater@metaswitch.com or by
# post at Metaswitch Networks Ltd, 100 Church St, Enfield EN2 6BQ, UK
#
# Special Exception
# Metaswitch Networks Ltd  grants you permission to copy, modify,
# propagate, and distribute a work formed by combining OpenSSL with The
# Software, or a work derivative of such a combination, even if such
# copying, modification, propagation, or distribution would otherwise
# violate the terms of the GPL. You must comply with the GPL in all
# respects for all of the code used other than OpenSSL.
# "OpenSSL" means OpenSSL toolkit software distributed by the OpenSSL
# Project and licensed under the OpenSSL Licenses, or a work based on such
# software and licensed under the OpenSSL Licenses.
# "OpenSSL Licenses" means the OpenSSL License and Original SSLeay License
# under which the OpenSSL Project distributes the OpenSSL toolkit software,
# as those licenses appear in the file LICENSE-OPENSSL.

MGMT_WHITELIST_DIR=/etc/clearwater-socket-factory/management.d
SIGNALING_WHITELIST_DIR=/etc/clearwater-socket-factory/signaling.d

get_daemon_args()
{
  . /etc/clearwater/config

  if [ ! -z $signaling_namespace ]
  then
    signaling_namespace="--signaling-namespace=$signaling_namespace"
  fi

  # The whitelists are comma separated lists of hosts. They're built up from
  # each line of each file in the correct directory. We also remove duplicates.
  if [ -d "$MGMT_WHITELIST_DIR" ] && [ "$(ls -A $MGMT_WHITELIST_DIR)" ]; then
    mgmt_allowed_hosts="--management-allowed-hosts=$(echo $(cat $MGMT_WHITELIST_DIR/* | sort | uniq) | sed -e 's/ /,/g')"
  fi

  if [ -d "$SIGNALING_WHITELIST_DIR" ] && [ "$(ls -A $SIGNALING_WHITELIST_DIR)" ]; then
    signaling_allowed_hosts="--signaling-allowed-hosts=$(echo $(cat $SIGNALING_WHITELIST_DIR/* | sort | uniq) | sed -e 's/ /,/g')"
  fi

  DAEMON_ARGS="$signaling_namespace
               $mgmt_allowed_hosts
               $signaling_allowed_hosts"
}

. /etc/clearwater/config
get_daemon_args
/usr/share/clearwater/bin/clearwater_socket_factory $DAEMON_ARGS
