#!/bin/sh
#
# Project Clearwater - IMS in the Cloud
# Copyright (C) 2014  Metaswitch Networks Ltd
#
# This program is free software: you can redistribute it and/or modify it
# under the terms of the GNU General Public License as published by the
# Free Software Foundation, either version 3 of the License, or (at your
# option) any later version, along with the "Special Exception" for use of
# the program along with SSL, set forth below. This program is distributed
# in the hope that it will be useful, but WITHOUT ANY WARRANTY;
# without even the implied warranty of MERCHANTABILITY or FITNESS FOR
# A PARTICULAR PURPOSE.  See the GNU General Public License for more
# details. You should have received a copy of the GNU General Public
# License along with this program.  If not, see
# <http://www.gnu.org/licenses/>.
#
# The author can be reached by email at clearwater@metaswitch.com or by
# post at Metaswitch Networks Ltd, 100 Church St, Enfield EN2 6BQ, UK
#
# Special Exception
# Metaswitch Networks Ltd  grants you permission to copy, modify,
# propagate, and distribute a work formed by combining OpenSSL with The
# Software, or a work derivative of such a combination, even if such
# copying, modification, propagation, or distribution would otherwise
# violate the terms of the GPL. You must comply with the GPL in all
# respects for all of the code used other than OpenSSL.
# "OpenSSL" means OpenSSL toolkit software distributed by the OpenSSL
# Project and licensed under the OpenSSL Licenses, or a work based on such
# software and licensed under the OpenSSL Licenses.
# "OpenSSL Licenses" means the OpenSSL License and Original SSLeay License
# under which the OpenSSL Project distributes the OpenSSL toolkit software,
# as those licenses appear in the file LICENSE-OPENSSL.
#

# This script fixes up the /etc/hosts file to have an entry that maps to the
# local address if it is IPv6.

. /etc/clearwater/config

# If the local IP address is an IPv6 address then the system needs a dummy
# hostname that maps to the address.

# Remove any entries that have been previously added by this script.
grep -v ' # added by clearwater-infrastructure 1hosts script' /etc/hosts | grep -v ' # maps to local IPv6 address' > /tmp/hosts.$$

# Determine whether the local IP address is an IPv6 address.
if /usr/share/clearwater/bin/is-address-ipv6 $local_ip
then
  # Generate the ip6.arpa hostname from the IP address.  Add it to the hosts file.
  hostname=$(/usr/share/clearwater/bin/ipv6-to-hostname $local_ip)
  echo $local_ip $hostname '# added by clearwater-infrastructure 1hosts script' >> /tmp/hosts.$$
fi

# Append the IPv6 localhost.  This is to satisfy RFC6761 section 6.3, namely
# "Users may assume that IPv4 and IPv6 address queries for localhost names
# will always resolve to the respective IP loopback address."
echo '::1 localhost # added by clearwater-infrastructure 1hosts script' >> /tmp/hosts.$$

# Compare the new hosts file with the existing one.  If it has changed overwrite
# the existing file and restart dnsmasq to pick up the changes, otherwise just
# remove the new file.

if diff /etc/hosts /tmp/hosts.$$ > /dev/null ;
then
  rm /tmp/hosts.$$
else
  mv /tmp/hosts.$$ /etc/hosts
  service dnsmasq restart
fi
