#!/bin/sh

# @file hostname
#
# Project Clearwater - IMS in the Cloud
# Copyright (C) 2013  Metaswitch Networks Ltd
#
# This program is free software: you can redistribute it and/or modify it
# under the terms of the GNU General Public License as published by the
# Free Software Foundation, either version 3 of the License, or (at your
# option) any later version, along with the "Special Exception" for use of
# the program along with SSL, set forth below. This program is distributed
# in the hope that it will be useful, but WITHOUT ANY WARRANTY;
# without even the implied warranty of MERCHANTABILITY or FITNESS FOR
# A PARTICULAR PURPOSE.  See the GNU General Public License for more
# details. You should have received a copy of the GNU General Public
# License along with this program.  If not, see
# <http://www.gnu.org/licenses/>.
#
# The author can be reached by email at clearwater@metaswitch.com or by
# post at Metaswitch Networks Ltd, 100 Church St, Enfield EN2 6BQ, UK
#
# Special Exception
# Metaswitch Networks Ltd  grants you permission to copy, modify,
# propagate, and distribute a work formed by combining OpenSSL with The
# Software, or a work derivative of such a combination, even if such
# copying, modification, propagation, or distribution would otherwise
# violate the terms of the GPL. You must comply with the GPL in all
# respects for all of the code used other than OpenSSL.
# "OpenSSL" means OpenSSL toolkit software distributed by the OpenSSL
# Project and licensed under the OpenSSL Licenses, or a work based on such
# software and licensed under the OpenSSL Licenses.
# "OpenSSL Licenses" means the OpenSSL License and Original SSLeay License
# under which the OpenSSL Project distributes the OpenSSL toolkit software,
# as those licenses appear in the file LICENSE-OPENSSL.

# Read our config file.
. /etc/clearwater/config

grep -v ' #+clearwater-infrastructure$' /etc/hosts > /tmp/hosts.$$

rc=$?;
if [ $rc != 0 ];
then
  echo "ERROR: unable to copy /etc/hosts to a temporary file"
  exit $rc
fi

# Check if the public hostname is actually an IPv4 address or an IPv6 address.
if echo $public_hostname | egrep -v -q -e '^[0-9.]+$' -e '^[0-9A-Fa-f:]+$'
then
  # If not, set that as the server's internal hostname.
  echo $public_hostname > /etc/hostname

  rc=$?;
  if [ $rc != 0 ];
  then
    echo "ERROR: unable to write to /etc/hostname"
    exit $rc
  fi
fi

# Ensure that the local hostname is resolvable (regardless of whether it was us that set it or not)
hostname $(cat /etc/hostname)
echo $local_ip $(cat /etc/hostname) '#+clearwater-infrastructure' >> /tmp/hosts.$$

rc=$?;
if [ $rc != 0 ];
then
  echo "ERROR: unable to write to /tmp/hosts.$$"
  exit $rc
fi

mv /tmp/hosts.$$ /etc/hosts

rc=$?;
if [ $rc != 0 ];
then
  echo "ERROR: unable to move /tmp/hosts.$$ to /etc/hosts"
  exit $rc
fi
