#!/bin/bash

# @file mmonit
#
# Project Clearwater - IMS in the Cloud
# Copyright (C) 2013  Metaswitch Networks Ltd
#
# This program is free software: you can redistribute it and/or modify it
# under the terms of the GNU General Public License as published by the
# Free Software Foundation, either version 3 of the License, or (at your
# option) any later version, along with the "Special Exception" for use of
# the program along with SSL, set forth below. This program is distributed
# in the hope that it will be useful, but WITHOUT ANY WARRANTY;
# without even the implied warranty of MERCHANTABILITY or FITNESS FOR
# A PARTICULAR PURPOSE.  See the GNU General Public License for more
# details. You should have received a copy of the GNU General Public
# License along with this program.  If not, see
# <http://www.gnu.org/licenses/>.
#
# The author can be reached by email at clearwater@metaswitch.com or by
# post at Metaswitch Networks Ltd, 100 Church St, Enfield EN2 6BQ, UK
#
# Special Exception
# Metaswitch Networks Ltd  grants you permission to copy, modify,
# propagate, and distribute a work formed by combining OpenSSL with The
# Software, or a work derivative of such a combination, even if such
# copying, modification, propagation, or distribution would otherwise
# violate the terms of the GPL. You must comply with the GPL in all
# respects for all of the code used other than OpenSSL.
# "OpenSSL" means OpenSSL toolkit software distributed by the OpenSSL
# Project and licensed under the OpenSSL Licenses, or a work based on such
# software and licensed under the OpenSSL Licenses.
# "OpenSSL Licenses" means the OpenSSL License and Original SSLeay License
# under which the OpenSSL Project distributes the OpenSSL toolkit software,
# as those licenses appear in the file LICENSE-OPENSSL.


# Read the config.
. /etc/clearwater/config

# Destination file location
MMONIT_CONFIG_FILE="/etc/monit/conf.d/mmonit.monit"

# User credentials for logging into local monit daemon
MONIT_USER="admin"
MONIT_PW="monit"

# Check if we have configuration for M/Monit
if [[ -z $mmonit_hostname || -z $mmonit_username || -z $mmonit_password ]]
then
  echo "Configuring monit for only localhost access"
  cat > $MMONIT_CONFIG_FILE << EOF
  set eventqueue basedir /var/monit/ slots 1000
  set httpd port 2812 and use address localhost
    allow 0.0.0.0/0
EOF
else
  echo "Configuring monit for localhost and M/Monit access"
  cat > $MMONIT_CONFIG_FILE << EOF
  set eventqueue basedir /var/monit/ slots 1000
  set mmonit http://$mmonit_username:$mmonit_password@$mmonit_hostname/collector
  set httpd port 2812 and use address $local_ip
    allow 0.0.0.0/0
    allow $MONIT_USER:$MONIT_PW
EOF
fi

