#!/bin/bash

# @file sas_socket_factory
#
# Copyright (C) Metaswitch Networks
# If license terms are provided to you in a COPYING file in the root directory
# of the source code repository by which you are accessing this code, then
# the license outlined in that COPYING file applies to your use.
# Otherwise no rights are granted except for those provided to you by
# Metaswitch Networks in a separate written agreement.

# Create /etc/clearwater-socket-factory/management.d/clearwater-infrastructure
# containing the node's SAS address for clearwater-socket-factory's management
# namespace whitelist. This allows Clearwater processes to connect to SAS.

signaling_cfg_dir=/etc/clearwater-socket-factory/signaling.d
management_cfg_dir=/etc/clearwater-socket-factory/management.d

mkdir -p $signaling_cfg_dir
mkdir -p $management_cfg_dir

. /etc/clearwater/config

if [ ! -z $sas_server ]; then
  if [ "$sas_use_signaling_interface" == "Y" ]; then
    echo "$sas_server" > $signaling_cfg_dir/clearwater-infrastructure
    rm -f $management_cfg_dir/clearwater-infrastructure
  else
    echo "$sas_server" > $management_cfg_dir/clearwater-infrastructure
    rm -f $signaling_cfg_dir/clearwater-infrastructure
  fi
else
  rm -f $management_cfg_dir/clearwater-infrastructure
  rm -f $signaling_cfg_dir/clearwater-infrastructure
fi
