#!/bin/bash

# @file sas_socket_factory
#
# Copyright (C) Metaswitch Networks 2018

# Create /etc/clearwater-socket-factory/management.d/clearwater-infrastructure
# containing the node's SAS addresses for clearwater-socket-factory's management
# namespace whitelist. This allows Clearwater processes to connect to SAS.
#
# Creates /etc/clearwater-socket-factory/signaling.d/clearwater-infrastructure
# instead if sas_use_signaling_interface is set to "Y" in shared_config.

. /etc/clearwater/config
python /usr/share/clearwater/bin/sas_socket_factory.py "$sas_use_signaling_interface"
