#!/bin/bash
#
# Copyright (C) Metaswitch Networks 2016
# If license terms are provided to you in a COPYING file in the root directory
# of the source code repository by which you are accessing this code, then
# the license outlined in that COPYING file applies to your use.
# Otherwise no rights are granted except for those provided to you by
# Metaswitch Networks in a separate written agreement.
#

# This script sets the log level for the local node.
. /usr/share/clearwater/infrastructure/install/common

LOG_LEVEL=$1
if [ "$LOG_LEVEL" == "debug" ]
then
  NEW_ENTRY=log_level=5
elif [ "$LOG_LEVEL" == "normal" ]
then
  NEW_ENTRY=
else
  echo Error: invalid parameter or no parameter specified.
  echo ""
  echo Usage:
  echo "$0 [normal|debug]"
  exit 1
fi

# Touch the file so that we can guarantee that it's present.
touch /etc/clearwater/user_settings user_settings
add_section_text /etc/clearwater/user_settings user_settings "$NEW_ENTRY"

echo Log level updated
cw-restart_node_processes
