#!/bin/sh
. /etc/clearwater/config

# If the local IP address is an IPv6 address then the system needs a dummy
# hostname that maps to the address.

# Remove any previous dummy hostname from the hosts file.
grep -v ' # maps to local IPv6 address' /etc/hosts > /tmp/hosts.$$

# Determine whether the local IP address is an IPv6 address.
python /usr/share/clearwater/bin/is_address_ipv6.py $local_ip
is_ipv6_address=$?

if [ $is_ipv6_address = 1 ] ;
then
  # Generate the ip6.ara hostname from the IP address.  Add it to the hosts file.
  hostname=$(python /usr/share/clearwater/bin/generate_ipv6_hostname.py $local_ip)
  echo $local_ip $hostname '# maps to local IPv6 address' >> /tmp/hosts.$$
fi

# Compare the new hosts file with the existing one.  If it has changed overwrite
# the existing file and restart dnsmasq to pick up the changes, otherwise just
# remove the new file.

if diff /etc/hosts /tmp/hosts.$$ > /dev/null ;
then
  rm /tmp/hosts.$$
else
  mv /tmp/hosts.$$ /etc/hosts
  service dnsmasq restart
fi
