#!/bin/sh

# @file cassandra
#
# Project Clearwater - IMS in the Cloud
# Copyright (C) 2013  Metaswitch Networks Ltd
#
# This program is free software: you can redistribute it and/or modify it
# under the terms of the GNU General Public License as published by the
# Free Software Foundation, either version 3 of the License, or (at your
# option) any later version, along with the "Special Exception" for use of
# the program along with SSL, set forth below. This program is distributed
# in the hope that it will be useful, but WITHOUT ANY WARRANTY;
# without even the implied warranty of MERCHANTABILITY or FITNESS FOR
# A PARTICULAR PURPOSE.  See the GNU General Public License for more
# details. You should have received a copy of the GNU General Public
# License along with this program.  If not, see
# <http://www.gnu.org/licenses/>.
#
# The author can be reached by email at clearwater@metaswitch.com or by
# post at Metaswitch Networks Ltd, 100 Church St, Enfield EN2 6BQ, UK
#
# Special Exception
# Metaswitch Networks Ltd  grants you permission to copy, modify,
# propagate, and distribute a work formed by combining OpenSSL with The
# Software, or a work derivative of such a combination, even if such
# copying, modification, propagation, or distribution would otherwise
# violate the terms of the GPL. You must comply with the GPL in all
# respects for all of the code used other than OpenSSL.
# "OpenSSL" means OpenSSL toolkit software distributed by the OpenSSL
# Project and licensed under the OpenSSL Licenses, or a work based on such
# software and licensed under the OpenSSL Licenses.
# "OpenSSL Licenses" means the OpenSSL License and Original SSLeay License
# under which the OpenSSL Project distributes the OpenSSL toolkit software,
# as those licenses appear in the file LICENSE-OPENSSL.

. /etc/clearwater/config

# Determine whether the local IP address is an IPv6 address.
python /usr/share/clearwater/bin/is_address_ipv6.py $local_ip
is_ipv6_address=$?

if [ $is_ipv6_address = 1 ] ;
then
  # Setup the variables to be used in the cassandra configuration files.
  seeds="$local_ip"

  # Enable IPv6 by not preferring IPv4.
  prefer_ipv4="# JVM_OPTS=\"$JVM_OPTS-Djava.net.preferIPv4Stack=true\""
else
  seeds="127.0.0.1"

  # Disable IPv6 by preferring IPv4.
  prefer_ipv4="JVM_OPTS=\"$JVM_OPTS-Djava.net.preferIPv4Stack=true\""
fi

# Update the configuration in cassandra.yaml and cassangra-env.sh
sed -e "s/^listen_address: .*$/listen_address: $local_ip/g
        s/^.*seeds:.*$/          - seeds: \"$seeds\"/g" </etc/cassandra/cassandra.yaml > /tmp/cassandra.yaml
mv /tmp/cassandra.yaml /etc/cassandra/cassandra.yaml

sed -e "s/^.*preferIPv4Stack.*$/$prefer_ipv4/g" </etc/cassandra/cassandra-env.sh > /tmp/cassandra-env.sh
mv /tmp/cassandra-env.sh /etc/cassandra/cassandra-env.sh
