clearwater-memcached/* /

# Install etcd plugins
clearwater-etcd-plugins/clearwater-memcached/memcached_plugin.py /usr/share/clearwater/clearwater-cluster-manager/plugins/
learwater-etcd-plugins/clearwater-memcached/memcached_remote_plugin.py /usr/share/clearwater/clearwater-cluster-manager/plugins/
clearwater-etcd-plugins/clearwater-memcached/memcached_utils.py /usr/share/clearwater/clearwater-cluster-manager/plugins/
