clearwater-socket-factory/clearwater_socket_factory /usr/share/clearwater/bin/
clearwater-socket-factory/clearwater-socket-factory-common /usr/share/clearwater/bin/
clearwater-socket-factory/clearwater-socket-factory-mgmt-service /usr/share/clearwater/bin/
clearwater-socket-factory/clearwater-socket-factory-sig-service /usr/share/clearwater/bin/
clearwater-socket-factory/clearwater-socket-factory-mgmt.conf /etc/init
clearwater-socket-factory/clearwater-socket-factory-sig.conf /etc/init
