#!/bin/sh

# @file memcached
#
# Project Clearwater - IMS in the Cloud
# Copyright (C) 2013  Metaswitch Networks Ltd
#
# This program is free software: you can redistribute it and/or modify it
# under the terms of the GNU General Public License as published by the
# Free Software Foundation, either version 3 of the License, or (at your
# option) any later version, along with the "Special Exception" for use of
# the program along with SSL, set forth below. This program is distributed
# in the hope that it will be useful, but WITHOUT ANY WARRANTY;
# without even the implied warranty of MERCHANTABILITY or FITNESS FOR
# A PARTICULAR PURPOSE.  See the GNU General Public License for more
# details. You should have received a copy of the GNU General Public
# License along with this program.  If not, see
# <http://www.gnu.org/licenses/>.
#
# The author can be reached by email at clearwater@metaswitch.com or by
# post at Metaswitch Networks Ltd, 100 Church St, Enfield EN2 6BQ, UK
#
# Special Exception
# Metaswitch Networks Ltd  grants you permission to copy, modify,
# propagate, and distribute a work formed by combining OpenSSL with The
# Software, or a work derivative of such a combination, even if such
# copying, modification, propagation, or distribution would otherwise
# violate the terms of the GPL. You must comply with the GPL in all
# respects for all of the code used other than OpenSSL.
# "OpenSSL" means OpenSSL toolkit software distributed by the OpenSSL
# Project and licensed under the OpenSSL Licenses, or a work based on such
# software and licensed under the OpenSSL Licenses.
# "OpenSSL Licenses" means the OpenSSL License and Original SSLeay License
# under which the OpenSSL Project distributes the OpenSSL toolkit software,
# as those licenses appear in the file LICENSE-OPENSSL.

NAME=memcached
INITD_PATH=/etc/init.d/$NAME
DEFAULT_PATH=/etc/default/$NAME

. /etc/clearwater/config

# On an IPv6 system memcached need to be configured to listen on the hostname
# that maps to the local IP address.
listen_address=$local_ip

if /usr/share/clearwater/bin/is_address_ipv6.py $local_ip
then
  listen_address=$(/usr/share/clearwater/bin/ipv6_to_hostname.py $local_ip)
fi

sed -e 's/^-l .*$/-l '$listen_address'/g
        s/^-m .*$/-m 512/g
        s/^# *-v *$/-v/g
        s/^\(# *\|\)-c.*$/-c 4096/g' </etc/memcached.conf >/etc/memcached_11211.conf

# Update init.d script to run daemon in context of $namespace_prefix

[ -z $signaling_namespace ] || namespace_prefix="ip netns exec $signaling_namespace"

INITD_TEMP=$(mktemp -t $NAME-initd.XXXXXX) || exit 1

sed 's/^\(\s\{1,\}\)\(\<start-stop-daemon\>.*--\<start\>.*\)$/\1$namespace_prefix \2 # clearwater-infrastructure/' $INITD_PATH > $INITD_TEMP

if ! cmp -s $INITD_PATH $INITD_TEMP
then
  # initd script update needed, so copy the $namespace_prefix mod
  cp $INITD_TEMP $INITD_PATH
fi

rm $INITD_TEMP


# Update default configuration with $namespace_prefix if needed

DEFAULT_TEMP=$(mktemp -t $NAME-default.XXXXXX) || exit 1

if [ -f $DEFAULT_PATH ]
then
  cat $DEFAULT_PATH | grep -v "# clearwater-infrastructure" > $DEFAULT_TEMP
else
  touch $DEFAULT_TEMP
  chmod +r $DEFAULT_TEMP
fi

echo "namespace_prefix=\"$namespace_prefix\" # clearwater-infrastructure" >> $DEFAULT_TEMP

if ! cmp -s $DEFAULT_PATH $DEFAULT_TEMP
then
  # default configuration update needed, so copy the change and
  # restart the service
  cp $DEFAULT_TEMP $DEFAULT_PATH
  service $NAME stop
fi

rm $DEFAULT_TEMP

