TARGETS := is-address-ipv6 bracket-ipv6-address ipv6-to-hostname issue-alarm

is-address-ipv6_SOURCES := is-address-ipv6.cpp
bracket-ipv6-address_SOURCES := bracket-ipv6-address.cpp
ipv6-to-hostname_SOURCES := ipv6-to-hostname.cpp
issue-alarm_SOURCES := issue-alarm.cpp
issue-alarm_LDFLAGS := -lzmq

include ../build-infra/cpp.mk
