#!/bin/bash
#
# Project Clearwater - IMS in the Cloud
# Copyright (C) 2014  Metaswitch Networks Ltd
#
# This program is free software: you can redistribute it and/or modify it
# under the terms of the GNU General Public License as published by the
# Free Software Foundation, either version 3 of the License, or (at your
# option) any later version, along with the "Special Exception" for use of
# the program along with SSL, set forth below. This program is distributed
# in the hope that it will be useful, but WITHOUT ANY WARRANTY;
# without even the implied warranty of MERCHANTABILITY or FITNESS FOR
# A PARTICULAR PURPOSE.  See the GNU General Public License for more
# details. You should have received a copy of the GNU General Public
# License along with this program.  If not, see
# <http://www.gnu.org/licenses/>.
#
# The author can be reached by email at clearwater@metaswitch.com or by
# post at Metaswitch Networks Ltd, 100 Church St, Enfield EN2 6BQ, UK
#
# Special Exception
# Metaswitch Networks Ltd  grants you permission to copy, modify,
# propagate, and distribute a work formed by combining OpenSSL with The
# Software, or a work derivative of such a combination, even if such
# copying, modification, propagation, or distribution would otherwise
# violate the terms of the GPL. You must comply with the GPL in all
# respects for all of the code used other than OpenSSL.
# "OpenSSL" means OpenSSL toolkit software distributed by the OpenSSL
# Project and licensed under the OpenSSL Licenses, or a work based on such
# software and licensed under the OpenSSL Licenses.
# "OpenSSL Licenses" means the OpenSSL License and Original SSLeay License
# under which the OpenSSL Project distributes the OpenSSL toolkit software,
# as those licenses appear in the file LICENSE-OPENSSL.
#

#
# Add informsink entries to /etc/snmp/snmpd.conf based upon the snmp_ip
# Clearwater config setting.
#

START_MARK="# Project Clearwater informsink start"
END_MARK="# Project Clearwater informsink end"

. /etc/clearwater/config

# Create a temporary copy of snmpd.conf with contents up to the start of
# Clearwater informsink definitions.

sed '1,/'"$START_MARK"'/ !d' /etc/snmp/snmpd.conf > /tmp/snmpd.conf.$$

# Add informslink definitions to end of temporary copy based upon comma
# seperated list of hosts defined by snmp_ip.

IFS=',' read -a SNMP_HOSTS <<< "$snmp_ip"

for HOST in "${SNMP_HOSTS[@]}";
do
  echo "informsink $HOST clearwater" >> /tmp/snmpd.conf.$$
done

# Copy remainder of snmpd.conf from the end of informsink definitions to
# the temporary copy.

sed '/'"$END_MARK"'/,$ !d' /etc/snmp/snmpd.conf >> /tmp/snmpd.conf.$$

# Compare original with the temporary copy. If it has changed replace
# the original and trigger an snmpd restart to pick up the changes,
# otherwise remove the temporary copy.

diff /etc/snmp/snmpd.conf /tmp/snmpd.conf.$$ > /dev/null

if [ $? -ne 0 ];
then
  mv /tmp/snmpd.conf.$$ /etc/snmp/snmpd.conf

  service snmpd restart
else
  rm /tmp/snmpd.conf.$$
fi

#
# Create the folder to store the statistics UNIX domain sockets.
#
mkdir -p /var/run/clearwater/stats
chmod -R o+wr /var/run/clearwater/stats
